import liff, { init } from './liff'

export default async () => {
  const root = window.document.getElementById('root')
  if (!root) {
    throw new Error('this is unreached')
  }

  try {
    await init()

    const { friendFlag: isFriend } = await liff.getFriendship()

    const profile = await liff.getProfile()
    root.innerHTML = `
      <div>generated by liff-app-template</div>
      <div>${profile.displayName}</div>
      <img src=${profile.pictureUrl}>
      <div>${isFriend ? 'friend' : 'not'}</div>
    `
  }
  catch(error) {
    root.innerHTML = `<pre>${error}</pre>`
  }
}
